export const QUESTION_CREATE_REQUEST = "QUESTION_CREATE_REQUEST";
export const QUESTION_CREATE_SUCCESS = "QUESTION_CREATE_SUCCESS";
export const QUESTION_CREATE_FAIL = "QUESTION_CREATE_FAIL";
export const QUESTION_CREATE_RESET = "QUESTION_CREATE_RESET";

export const QUESTION_LIST_REQUEST = "QUESTION_LIST_REQUEST";
export const QUESTION_LIST_SUCCESS = "QUESTION_LIST_SUCCESS";
export const QUESTION_LIST_FAIL = "QUESTION_LIST_FAIL";
export const QUESTION_LIST_RESET = "QUESTION_LIST_RESET";

export const QUESTION_DETAILS_REQUEST = "QUESTION_DETAILS_REQUEST";
export const QUESTION_DETAILS_SUCCESS = "QUESTION_DETAILS_SUCCESS";
export const QUESTION_DETAILS_FAIL = "QUESTION_DETAILS_FAIL";

export const QUESTION_CREATE_ANSWER_REQUEST = "QUESTION_CREATE_ANSWER_REQUEST";
export const QUESTION_CREATE_ANSWER_SUCCESS = "QUESTION_CREATE_ANSWER_SUCCESS";
export const QUESTION_CREATE_ANSWER_FAIL = "QUESTION_CREATE_ANSWER_FAIL";
export const QUESTION_CREATE_ANSWER_RESET = "QUESTION_CREATE_ANSWER_RESET";

export const ANSWER_UPDATE_REQUEST = "ANSWER_UPDATE_REQUEST";
export const ANSWER_UPDATE_SUCCESS = "ANSWER_UPDATE_SUCCESS";
export const ANSWER_UPDATE_FAIL = "ANSWER_UPDATE_FAIL";
export const ANSWER_UPDATE_RESET = "ANSWER_UPDATE_RESET";
