export const PROBLEM_CREATE_REQUEST = "PROBLEM_CREATE_REQUEST";
export const PROBLEM_CREATE_SUCCESS = "PROBLEM_CREATE_SUCCESS";
export const PROBLEM_CREATE_FAIL = "PROBLEM_CREATE_FAIL";
export const PROBLEM_CREATE_RESET = "QUESTION_CREATE_RESET";

export const PROBLEM_LIST_REQUEST = "PROBLEM_LIST_REQUEST";
export const PROBLEM_LIST_SUCCESS = "PROBLEM_LIST_SUCCESS";
export const PROBLEM_LIST_FAIL = "PROBLEM_LIST_FAIL";
export const PROBLEM_LIST_RESET = "PROBLEM_LIST_RESET";
